name: Uso de artefactos
on: push

jobs:
  subida:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: subir archivo
        uses: actions/upload-artifact@v4
        with:
          name: archivo-subido
          path: ./.github/actions/actions1/action.yml

  bajada:
    runs-on: ubuntu-latest
    steps:
      - name: coger archivo
        uses: actions/download-artifact@v4
        with:
          name: archivo-subido
      - run: cat action.yml
