name: Llamar a acción
on: push

jobs:
  llamar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/actions1
      - name: comprobar archivo
        run: cat archivo.txt

