name: Ejercicio 1 de Contexts
on: workflow_dispatch

jobs:
  info_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir info del runner
        run: |
          echo "Sistema operativo ${{ runner.os }}"
          echo "Arquitectura ${{ runner.arch }}"
          echo "Espacio disponible"
          df -h

