name: Ejercicio 4 de Contexts
on:
  pull_request:
    types: opened
jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
          if [ ${{ github.event.pull_request.title == "*urgent*"}} ]; then
            echo "${{ github.event.pull_request.title }}"
          fi


