name: Ejercicio 2 de Contexts
on: push

jobs:
  despliegue:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue en main
        run: |
          if [ ${{ github.ref_name}} == 'main' ]; then
            echo "hola"
          else
            echo "adios"
          fi

