name: reusable

on:
  workflow_call:
    inputs:
      environment:
        description: Elegir entorno
        required: true
        default: development
        type: string
    outputs:
      API_URL:
        description: url de la api
        value: ${{ jobs.devolver.outputs.api }}
      LOG_LEVEL:
        description: log_level
        value: ${{ jobs.devolver.outputs.log }}

jobs:
  devolver:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: devolver API_URL
        run: |
          echo "api=${{ vars.API_URL }}" >> $GITHUB_OUTPUT
          echo "log=${{ vars.LOG_LEVEL }}" >> $GITHUB_OUTPUT
