name: reusable

on:
  workflow_call:
    inputs:
      environment:
        description: Elegir entorno
        required: false
        default: development
        type: string
    outputs:
      API_URL:
        description: url de la api
        value: ${{ jobs.devolver.outputs.api }}
      LOG_LEVEL:
        description: log_level
        value: ${{ jobs.devolver.outputs.log }}

jobs:
  devolver:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: echo ${{ vars.API_URL }}
      - name: devolver API_URL
        run: |
          echo "api=${{ env.log }}" >> $GITHUB_OUTPUT
          echo "log=${{ env.api }}" >> $GITHUB_OUTPUT
        env:
          api: ${{ vars.API_URL }}
          log: ${{ vars.LOG_LEVEL }}
