name: Ejercicio 3 dispatch

on: 
  workflow_dispatch:
    inputs:
      confirm:
        required: true
        type: boolean
        

jobs:

  printInputs:
    runs-on: ubuntu-latest
    env:
      seleccion: ${{ inputs.confirm }}

    steps:
      - run: echo $seleccion   

