name: Imprimir
on: 
  workflow_call:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir cadena
        run: echo "Este texto se está imprimiendo en reusar_1.yml"
