name: Ejercicio 1 Variables y Outputs
on: workflow_dispatch

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - name: Definir variables
        run: |
          echo "nombre=rafa" >> "$GITHUB_OUTPUT"
          echo "apellido=gonzalez" >> "$GITHUB_OUTPUT"
      - name: Ejecutar comando
        run: echo "Mi nombre completo: $nombre"
