name: Ejercicio 2 Variables y Outputs
on: workflow_dispatch

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir secreto
        run: echo "Contenido del secreto -> ${{ secrets.MY_SECRET }}"
