name: Ejercicio 4 Variables y Outputs
on: 
  push:
    branches:
      - main
      - develop
jobs:
  json_read:
    runs-on: ubuntu-latest
    steps:
      - name: clonar repo
        uses: actions/checkout@v4
      - name: Leer json
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./archivo.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: a ver
        run: echo ${{ fromJson(env.PACKAGE_JSON).applications.version }}

      - name: print 
        run: echo ${{ github.ref_name }}
