name: Ejercicio 1 Variables y Outputs
on: workflow_dispatch
jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Definir variables de dos formas distintas
        id: def_vars
        run: |
          echo "nombre=Rafaeñ" >> $GITHUB_OUTPUT
          echo "apellido=González" >> $GITHUB_ENV
      - name: Ejecutar comando
        run: echo "Mi nombre completo -> ${{ steps.def_vars.outputs.nombre }} ${{ env.apellido }}"
